config/routes.rb
Rails.application.routes.draw do
  resources :signups, only: %w[index]
  resources :credentials, only: %w[create index] do
    delete :delete_all, on: :collection
  end
  root "signup#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/credential.rb
require 'benchmark'
class Credential < ApplicationRecord
  include ActionView::Helpers::NumberHelper

  PWLIST = File.read(Rails.root.join("db/pwlist.txt")).lines.map(&:chomp)

  def masked_password
    return "***" if password.length <= 2

    "#{password[0, 2]}********"
  end

  def weaknesses
    return @weaknesses if defined?(@weaknesses)

    check = NOBSPW::PasswordChecker.new(**self.slice(%i[password name email]).symbolize_keys)
    reasons = check.reasons.map { |reason| reason.to_s.tr("_", " ") }
    reasons.unshift(pwlist_reason) if pwlist_reason
    @weaknesses = reasons.join(", ").presence || "✨⭐💯"
  end

  def pwlist_reason
    return @pwlist_reason if defined?(@pwlist_reason)


    index = PWLIST.index(password)
    return unless index

    number = number_with_delimiter(index + 1)
    @pwlist_reason = "##{number} most commonly used"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/credentials_controller.rb
class CredentialsController < ApplicationController
  def index
    @credentials = Credential.all.sort_by { |c| -c.weaknesses.length }
  end

  def create
    Credential.create(credentials_params)
  end

  def delete_all
    Credential.destroy_all
    redirect_to credentials_path
  end

  private

  def credentials_params
    params.require(:credential).permit(:name, :email, :password)
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/credentials/index.html.erb
<div class="container">
  <h1>Password Analysis</h1>
  <% if @credentials.any? %>
    <table class="credentials-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Password</th>
          <th>Weaknesses</th>
          <th>Time to Crack</th>
        </tr>
      </thead>
      <tbody>
        <% @credentials.each do |credential| %>
          <tr class="fade-row">
            <td><%= credential.name %></td>
            <td><%= credential.masked_password %></td>
            <td><%= credential.weaknesses %></td>
            <td class="password" data-password="<%= credential.password %>"></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= button_to 'Delete Everything', delete_all_credentials_path,
                  method: :delete,
                  class: 'reset fade-row',
                  style: 'display: none',
                  data: { turbo_action: "replace", turbo_frame: "_top" } %>
  <% else %>
    <h2><em>There's nothing here. Nobody has signed up.</em></h2>
  <% end %>
</div>

<script src="/passwordtester.js"></script>
<script>
  const analyze = zxcvbn; // from passwordtester.js
  if (!analyze) {
    console.error('zxcvbn library is not loaded.');
  }

  document.addEventListener("DOMContentLoaded", () => {
    const rows = document.querySelectorAll(".fade-row");
    let currentIndex = 0;

    document.body.addEventListener("click", () => {
      if (currentIndex < rows.length) {
        rows[currentIndex].style.display = "";
        rows[currentIndex].style.opacity = 1;
        currentIndex++;
      }
    });

    // Initialize rows with opacity 0
    rows.forEach(row => row.style.opacity = 0);
    rows.forEach(function(row) {
      const cell = row.querySelector(".password");
      const password = cell.getAttribute("data-password");
      const analysis = analyze(password);
      cell.textContent = analysis.crack_times_display.offline_slow_hashing_1e4_per_second;
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "SafeNet Academy" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag :all, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="<%= controller_name %>">
    <%= yield %>
  </body>
</html>

app/views/signup/index.html.erb
<div class="container">
  <h1>SafeNet Academy</h1>
  <img class="logo" src="/logo.png">
	<%= form_for :credential, url: credentials_path, remote: true, html: { autocomplete: 'off' } do |f| %>
		<div class="signup-form">
			<%= f.text_field :name, placeholder: "Name", required: true, autocomplete: 'off' %>
			<%= f.text_field :email, placeholder: "Email", autocomplete: 'off' %>
			<%= f.password_field :password, placeholder: "Password", required: true, autocomplete: 'off' %>
			<button type="submit">Start the Class</button>
		</div>
	<% end %>

  <div id="thank-you-modal" class="thank-you-modal">
    Thank you for registering! Please have a seat.
  </div>

  <script>
    document.addEventListener("DOMContentLoaded", () => {
      const form = document.querySelector("form");
      const name = document.querySelector("input#credential_name");
      const modal = document.getElementById("thank-you-modal");

      form.addEventListener("turbo:submit-end", () => {
        form.reset();
        name.focus();
        setTimeout(() => {
          modal.style.opacity = 1;
          setTimeout(() => {
            modal.style.opacity = 0;
          }, 3000);
        }, 0);
      });
    });
  </script>
</div>